### ISSUE TITLE
Date and Time Format Issue

### ISSUE THREAD

**Issue by hashim-zhd** [sunalive/jSunPicker#1]
Hi,

I'm getting this response "1466812800000" after submitting form in PHP. Submitting time and date from the form in this format 25 Jun 2016, 07:25 PM. Kindly let me know, What is the problem?

**Comment by sunalive** [comment]
Did you check the '**_Output Format_**' option?  What you see on screen is the 'Display Format'.  'Output Format' is '**_U - Unix date time_**' by default (which is what is being submitted).  You'll have to set the output format to your desired format.  You can check the documentation here [http://sunalive.github.io/jSunPicker/](http://sunalive.github.io/jSunPicker/)

Let me know if that worked.

Ravi.
